echo "/////////////////"
echo "/////////////////"
echo "/////////////////"
echo "/////////////////"
echo "/////////////////"
echo "/////////////////"
echo "/////////////////"
echo "/////////////////"
echo "/////////////////"
echo "/////////////////"
echo "/////////////////"
echo "/////////////////"
echo "-----------------"
clang -g main.c common/util.c ui/console.c repository/repository.c repository/test_repository.c domain/entities.c controller/controller.c controller/test_controller.c -o programdebug
echo "-----------------"
